# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  samplecouchbasenocache-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8091:8091
      - 127.0.0.1:8092:8092
      - 127.0.0.1:8093:8093
      - 127.0.0.1:8094:8094
      - 127.0.0.1:11210:11210
    environment:
      - BUCKET=sampleCouchbaseNoCache
    # volumes:
    #   - ~/volumes/jhipster/samplecouchbasenocache/couchbase/:/opt/couchbase/var
